import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs:[
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/tutorial-questionnaire'
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index'
      },
      collapsed:false,
      items:[
        'tutorials/firebase-setup',
        'tutorials/deploying-to-static-website',
        'tutorials/downloading-user-data'
      ]
    },
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'doc',
        id: 'typedoc/index'
      },
      items:[
        'typedoc/modules'
      ]
    }
  ]
};

// Sidebar if we want to include all interfaces
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   docs:[
//     'introduction',
//     {
//       type: 'category',
//       label: 'Getting Started',
//       link: {
//         type: 'generated-index',
//       },
//       collapsed: false,
//       items: [
//         'getting-started/installation',
//         'getting-started/tutorial-questionnaire'
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Tutorials',
//       link: {
//         type: 'generated-index'
//       },
//       collapsed:false,
//       items:[
//         'tutorials/firebase-setup',
//         'tutorials/deploying-to-static-website',
//         'tutorials/downloading-user-data'
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Documentation',
//       link: {
//         type: 'doc',
//         id: 'typedoc/index'
//       },
//       items:[
//         {
//           type: 'category',
//           label: 'Modules',
//           link: {
//             type: 'doc',
//             id: 'typedoc/modules'
//           },
//           items:[
//             {
//               type:'autogenerated',
//               dirName:'typedoc/interfaces'
//             }
//           ]
//         }
//       ]
//     }
//   ]
// };

export default sidebars;
