import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/index',
      },
      collapsed: false,
      items: [
        'getting-started/how-does-it-work',
        'getting-started/installation',
        'getting-started/your-first-study',
        'getting-started/collecting-data',
      ],
    },
    {
      type: 'category',
      label: 'Designing Studies',
      link: {
        type: 'doc',
        id: 'designing-studies/index',
      },
      collapsed: false,
      items: [
        'designing-studies/forms',
        'designing-studies/image-video-stimulus',
        'designing-studies/html-stimulus',
        'designing-studies/react-stimulus',
        'designing-studies/vega-stimulus',
        'designing-studies/answers-trainings',
        'designing-studies/study-sequences',
        'designing-studies/dynamic-blocks',
        'designing-studies/provenance-tracking',
        'designing-studies/think-aloud',
        'designing-studies/plugin-libraries',
        'designing-studies/applying-style'
      ],
    },
    {
      type: 'category',
      label: 'Data And Deployment',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'data-and-deployment/index',
      },
      items: [
        'data-and-deployment/firebase-setup',
        {
          type: 'category',
          label: 'Authentication and Authorization',
          link: {
            type: 'doc',
            id: 'data-and-deployment/authentication-authorization/index',
          },
          items: [
            'data-and-deployment/authentication-authorization/adding-removing-ui',
            'data-and-deployment/authentication-authorization/firebase-user-management',
          ],
        },
        'data-and-deployment/deploying-to-static-website',
        'data-and-deployment/prolific-integration',
        'data-and-deployment/lifecycle-of-revisit',
      ],
    },
    {
      type: 'category',
      label: 'Analysis',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'analysis/index',
      },
      items: [
        'analysis/data-management',
        'analysis/study-card',
        'analysis/table',
        'analysis/trial-stats',
        'analysis/data-export',
        'analysis/participant-replay',
      ],
    },
    {
      type: 'category',
      label: 'ReVISitPy',
      link: {
        type: 'doc',
        id: 'revisitpy/index',
      },
      collapsed: false,
      items: [
        'revisitpy/overview',
        'revisitpy/installation',
        {
          type: 'category',
          label: 'Examples',
          link: {
            type: 'doc',
            id: 'revisitpy/examples/index',
          },
          items: [
            'revisitpy/examples/example_simple_html',
            'revisitpy/examples/example_expanding_html_study',
            'revisitpy/examples/example_jnd_study',
          ],
        },
      ],
    },
    'faq',
  ],
  reference: [
    {
      type: 'category',
      label: 'TypeDoc',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'typedoc/index',
      },
      items: [
        {
          type: 'category',
          label: 'Interfaces',
          collapsed: false,
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'typedoc/interfaces',
            },
          ],
        },
        {
          type: 'category',
          label: 'Type Aliases',
          collapsed: false,
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'typedoc/type-aliases',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Libraries',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'libraries',
        },
      ],
    },
    {
      type: 'category',
      label: 'ReVISitPY Reference',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'revisitpy-reference',
        },
      ],
    },
  ],
};

export default sidebars;
