import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs:[
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/index'
      },
      collapsed: false,
      items: [
        'getting-started/how-does-it-work',
        'getting-started/installation',
        'getting-started/your-first-study',
        'getting-started/collecting-data'
      ],
    },
    {
      type: 'category',
      label: 'Designing Studies',
      link: {
        type: 'doc',
        id:'designing-studies/index'
      },
      collapsed:false,
      items:[
        'designing-studies/html-stimulus',
        'designing-studies/provenance-tracking',
        'designing-studies/react-stimulus',
        'designing-studies/study-sequences'
      ]
    },
    {
      type:'category',
      label:'Data And Deployment',
      link:{
        type:'doc',
        id:'data-and-deployment/index'
      },
      items:[
        'data-and-deployment/deploying-to-static-website',
        'data-and-deployment/firebase-setup',
        'data-and-deployment/lifecycle-of-revisit',
        {
          type: 'category',
          label: 'Authentication and Authorization',
          link: {
            type: 'doc',
            id: 'data-and-deployment/authentication-authorization/index'
          },
          items:[
            'data-and-deployment/authentication-authorization/adding-removing-ui',
            'data-and-deployment/authentication-authorization/firebase-user-management'
          ]
        },
      ]
    },
    {
      type:'category',
      label:'Analysis',
      link:{
        type:'doc',
        id:'analysis/index'
      },
      items:[
        'analysis/data-management',
        'analysis/dashboard',
        'analysis/tableview'
      ]
    },
    'faq',
    {
      type: 'category',
      label: 'TypeDoc',
      link: {
        type: 'doc',
        id: 'typedoc/index'
      },
      items:[
        {
          type: 'category',
          label: 'Modules',
          link: {
            type: 'doc',
            id: 'typedoc/globals'
          },
          items:[
            {
              type:'category',
              label: 'Interfaces',
              link:{
                type: 'generated-index',
              },
              items:[
                {
                  type:'autogenerated',
                  dirName:'typedoc/interfaces'
                }
              ]
            },
            {
              type:'category',
              label: 'Type Aliases',
              link:{
                type: 'generated-index',
              },
              items:[
                {
                  type:'autogenerated',
                  dirName:'typedoc/type-aliases'
                }
              ]
            },
          ]
        }
      ]
    }
  ]
};

// Sidebar if we want to include all interfaces
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   docs:[
//     'introduction',
//     {
//       type: 'category',
//       label: 'Getting Started',
//       link: {
//         type: 'generated-index',
//       },
//       collapsed: false,
//       items: [
//         'getting-started/installation',
//         'getting-started/tutorial-questionnaire'
//       ],
//     },
//     {
//       type: 'category',
//       label: 'designing-studies',
//       link: {
//         type: 'generated-index'
//       },
//       collapsed:false,
//       items:[
//         'designing-studies/firebase-setup',
//         'designing-studies/deploying-to-static-website',
//         'designing-studies/downloading-user-data'
//       ]
//     },
//     {
//       type: 'category',
//       label: 'Documentation',
//       link: {
//         type: 'doc',
//         id: 'typedoc/index'
//       },
//       items:[
//         {
//           type: 'category',
//           label: 'Modules',
//           link: {
//             type: 'doc',
//             id: 'typedoc/modules'
//           },
//           items:[
//             {
//               type:'autogenerated',
//               dirName:'typedoc/interfaces'
//             }
//           ]
//         }
//       ]
//     }
//   ]
// };

export default sidebars;
