name: Deploy To GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      # Build documentation repo
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build documentation
        run: yarn build

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        id: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: revisit.dev
